### PR TITLE
Users/skurnevich/fix change syntax func 292

### PR DESCRIPTION
**Pull request by skurnevich**
Fix for zowe/zlux#292

Corrected changeSyntax function content condition, to check on undefined and null, also replaced deprecated React method.

Thanks,
Sergei

### CODE REVIEW

**Comment by jordanCain** [comment]
@skurnevich  I've tested this with the MVS explorer (using the built version 0.0.12-pr-35-2-20200608160616) and i am still seeing an issue.

If I open a dataset/member that has no content I can add text to the editor view, if I change the syntax I can no longer add any text to the editor until I open a dataset/member that has content in it.

**Comment by skurnevich** [comment]
Hi @jordanCain, sounds like something different, as you unable to edit content, not just seeing old one, unfortunately I can't get that behaviour, could you please provide more detailed steps to reproduce? DS names also could be helpful. Thanks

**Comment by jordanCain** [comment]
@skurnevich Yes it's a different problem but seems like a regression. 
I can reliably reproduce by:
1. Create new dataset member
2. Open new dataset member
3. Add some text to the text editor
4. Change syntax highlighting
5. Try to enter more text to the text editor (Regression is here, previously I was able to do this - I verified I was able to do this using the Zowe 1.12.0 RC2 build) 

I have verified that your change does fix the original bug though

**Comment by skurnevich** [comment]
@jordanCain Ok, makes sense, thanks for the review, I'll check that

**Comment by skurnevich** [comment]
Hi @jordanCain, 

I have reviewed the described issue, and it seems to be not complete regression, but another appearance of zowe/zlux#369 issue. 
You could also reproduce it by trying to open completely empty ds, and switch syntax before typing, there will be a conflict of focus between the editor and modal part of material-ui select component. And as result - the editor window will be blocked until you click somewhere out of it. And it also seems to be an issue in chromium based browsers, at least Safari works fine for me.
Anyway I have fixed the call stack limit exception and created a [PR for that](https://github.com/zowe/explorer-mvs/pull/129)

I also reworked Orion editor as well, rolled back syntaxChange function, and added more logic to componentDidUpdate method. 
I have introduced a new flag parameter props.file to track if source file has been changed, as I can't find any other way to be 100% sure that source file has been changed.
Anyway it is not breaking change and code will work even without this property passed.
So initial issue is fixed, as well as an issue when you type something in editor window, switch syntax and lose unsaved changes.

Only one issue is still can be observed - you need two datasets (DS1, DS2) with equal content, empty will work fine for it. 
Change content of one DS1 then switch to DS2, those unsaved changes from DS1 will appear as DS2 content. However I hope it is quite rare bug. 
And this bug will be solved by props.file property. I will add it to the USS and MVS explorers to pass to the Orion editor when this PR will be merged.

Thanks

**Pull request merged**
